theme: jekyll-theme-cayman
title: TERMite
description: A library of rich terminal app utilities and visual elements such as progress indicators, cursor control and APIs for rendering and updating content in-place.
